language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.1
  - 7.2
  - nightly

env:
  - PREFER_LOWEST="--prefer-lowest --prefer-stable"
  - PREFER_LOWEST=""

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer update --no-interaction --optimize-autoloader --prefer-dist $PREFER_LOWEST
  - composer global require "phpunit/phpunit=~7.0"
  - composer global require "squizlabs/php_codesniffer=^3.0"

script:
  - phpunit
  - phpcs
